name: automatic release
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: 'https://registry.npmjs.org'
      - name: install can-npm-publish and dependencies
        run: |
          npm install can-npm-publish
          npm ci
      - name: check version and add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ./release.sh
      - name: build
        run: npm run build
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}