name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: pnpm install --frozen-lockfile
      - run: NODE_OPTIONS="--no-warnings" pnpm test